### PR TITLE
#167729777 setup unit test 

### PR DESCRIPTION
**Pull request by sebaztyn**
#### What does this PR do?
Set up unit testing suite for the project
#### Description of Task to be completed?
- install mocha, chai test suite
- set up a dedicated test folder
- write npm script to run tests
- run a simple test to confirm endpoint works

#### How should this be manually tested?
 - clone repository
- startup terminal
- cd into the cloned repository
- start test by typing ```npm test``` into the terminal

#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/167729777

#### Screenshots (if appropriate)
None
#### Questions:
None

### CODE REVIEW

**Review by mthamayor — CHANGES_REQUESTED** [review]
https://github.com/andela/shadowcat-backend/blob/80d10d986ae8898931eb3973f8c2c740ae6b2fc3/package.json#L11

Can you please make this line as dry as possible? Just run the test and don't worry about the code coverage. @davidfrank96 would handle that in his chore. 
Just 
```
cross-env NODE_ENV=test mocha src/test/*.test.js --require @babel/register --timeout 10000 --exit
```
Should suffice.

Secondly, You used `nyc` but in the devDependencies, `nyc` is not present. Please look into this.

**Review by mthamayor — CHANGES_REQUESTED** [review]
https://github.com/andela/shadowcat-backend/blob/311d0f26eda6fb7bfb8430c0dbe94abd443ecf3e/src/index.js#L96-L99

Great job so far. While testing your branch, I noticed the lines shown above are unreachable codes as they are not part of the routes.

A suggestion is moving those lines to the routes/index.js file and changing the `app.get` to `index.get`

**Review by mthamayor — APPROVED** [review]
Great work, man.

**Review by chibytez — APPROVED** [review]

**Review by okafor-chidimma — APPROVED** [review]
Well done. I approve

**Review by okabamac — APPROVED** [review]
Looks good to me

**Review by Stylll — APPROVED** [review]

**Pull request merged**
